// Autogenerated from Golubets (v1.2.0), do not edit directly.
// See also: https://pub.dev/packages/golubets

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
public final class GolubetsError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  public init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "GolubetsError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let golubetsError = error as? GolubetsError {
    return [
      golubetsError.code,
      golubetsError.message,
      golubetsError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualssegmented_control(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualssegmented_control(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualssegmented_control(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with golubetsets. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashsegmented_control(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashsegmented_control(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashsegmented_control(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Configuration data sent from Dart to the native side.
///
/// Generated class from Golubets that represents data sent in messages.
public struct CupertinoSegmentedConfig: Hashable {
  public init(
    choices: [String],
    selectedChoice: String? = nil,
    disabledChoices: [String] = [],
    thumbColor: Int64 = 4294967295,
    backgroundColor: Int64 = 0,
    padding: [Double] = [
      3, 
      2, 
      3, 
      2, 
    ],
    proportionalWidth: Bool = false,
    isMomentary: Bool = false
  ) {
    self.choices = choices
    self.selectedChoice = selectedChoice
    self.disabledChoices = disabledChoices
    self.thumbColor = thumbColor
    self.backgroundColor = backgroundColor
    self.padding = padding
    self.proportionalWidth = proportionalWidth
    self.isMomentary = isMomentary
  }
  let choices: [String]
  let selectedChoice: String?
  let disabledChoices: [String]
  let thumbColor: Int64
  let backgroundColor: Int64
  let padding: [Double]
  let proportionalWidth: Bool
  let isMomentary: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ golubetsVar_list: [Any?]) -> CupertinoSegmentedConfig? {
    let choices = golubetsVar_list[0] as! [String]
    let selectedChoice: String? = nilOrValue(golubetsVar_list[1])
    let disabledChoices = golubetsVar_list[2] as! [String]
    let thumbColor = golubetsVar_list[3] as! Int64
    let backgroundColor = golubetsVar_list[4] as! Int64
    let padding = golubetsVar_list[5] as! [Double]
    let proportionalWidth = golubetsVar_list[6] as! Bool
    let isMomentary = golubetsVar_list[7] as! Bool

    return CupertinoSegmentedConfig(
      choices: choices,
      selectedChoice: selectedChoice,
      disabledChoices: disabledChoices,
      thumbColor: thumbColor,
      backgroundColor: backgroundColor,
      padding: padding,
      proportionalWidth: proportionalWidth,
      isMomentary: isMomentary
    )
  }
  func toList() -> [Any?] {
    return [
      choices,
      selectedChoice,
      disabledChoices,
      thumbColor,
      backgroundColor,
      padding,
      proportionalWidth,
      isMomentary,
    ]
  }
  public static func == (lhs: CupertinoSegmentedConfig, rhs: CupertinoSegmentedConfig) -> Bool {
    return deepEqualssegmented_control(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashsegmented_control(value: toList(), hasher: &hasher)
  }
}

private class SegmentedControlGolubetsCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CupertinoSegmentedConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SegmentedControlGolubetsCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CupertinoSegmentedConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SegmentedControlGolubetsCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SegmentedControlGolubetsCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SegmentedControlGolubetsCodecWriter(data: data)
  }
}

class SegmentedControlGolubetsCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SegmentedControlGolubetsCodec(readerWriter: SegmentedControlGolubetsCodecReaderWriter())
}

/// Host API for creating and updating the native control.
///
/// Generated protocol from Golubets that represents a handler of messages from Flutter.
public protocol CupertinoSegmentedControlApi {
  /// Creates a new native view with the given [viewId] and initial [config].
  /// The [callback] will be used to send events back to Dart.
   func create(viewId: Int64, config: CupertinoSegmentedConfig) throws
  /// Updates an existing view identified by [viewId] with new [config].
   func update(viewId: Int64, config: CupertinoSegmentedConfig) throws
}

/// Generated setup class from Golubets to handle messages through the `binaryMessenger`.
public class CupertinoSegmentedControlApiSetup {
  static var codec: FlutterStandardMessageCodec { SegmentedControlGolubetsCodec.shared }
  /// Sets up an instance of `CupertinoSegmentedControlApi` to handle messages through the `binaryMessenger`.
  public static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CupertinoSegmentedControlApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Creates a new native view with the given [viewId] and initial [config].
    /// The [callback] will be used to send events back to Dart.
    let createChannel = FlutterBasicMessageChannel(name: "dev.bayori.golubets.platform_adaptive_widgets.CupertinoSegmentedControlApi.create\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let configArg = args[1] as! CupertinoSegmentedConfig
        do {
          try api.create(viewId: viewIdArg, config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createChannel.setMessageHandler(nil)
    }
    /// Updates an existing view identified by [viewId] with new [config].
    let updateChannel = FlutterBasicMessageChannel(name: "dev.bayori.golubets.platform_adaptive_widgets.CupertinoSegmentedControlApi.update\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let viewIdArg = args[0] as! Int64
        let configArg = args[1] as! CupertinoSegmentedConfig
        do {
          try api.update(viewId: viewIdArg, config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateChannel.setMessageHandler(nil)
    }
  }
}
