// Autogenerated from Golubets (v1.2.0), do not edit directly.
// See also: https://pub.dev/packages/golubets
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Configuration data sent from Dart to the native side.
class CupertinoSegmentedConfig {
  const CupertinoSegmentedConfig({
    required this.choices,
    this.selectedChoice,
    this.disabledChoices = const <String>[],
    this.thumbColor = 4294967295,
    this.backgroundColor = 0,
    this.padding = const <double>[
      3, 
      2, 
      3, 
      2, 
    ],
    this.proportionalWidth = false,
    this.isMomentary = false,
  });

  final List<String> choices;

  final String? selectedChoice;

  final List<String> disabledChoices;

  final int thumbColor;

  final int backgroundColor;

  final List<double> padding;

  final bool proportionalWidth;

  final bool isMomentary;

  List<Object?> _toList() {
    return <Object?>[
      choices,
      selectedChoice,
      disabledChoices,
      thumbColor,
      backgroundColor,
      padding,
      proportionalWidth,
      isMomentary,
    ];
  }

  Object encode() {
    return _toList();  }

  static CupertinoSegmentedConfig decode(Object result) {
    result as List<Object?>;
    return CupertinoSegmentedConfig(
      choices: (result[0] as List<Object?>?)!.cast<String>(),
      selectedChoice: result[1] as String?,
      disabledChoices: (result[2] as List<Object?>?)!.cast<String>(),
      thumbColor: result[3]! as int,
      backgroundColor: result[4]! as int,
      padding: (result[5] as List<Object?>?)!.cast<double>(),
      proportionalWidth: result[6]! as bool,
      isMomentary: result[7]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CupertinoSegmentedConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _GolubetsCodec extends StandardMessageCodec {
  const _GolubetsCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CupertinoSegmentedConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return CupertinoSegmentedConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API for creating and updating the native control.
class CupertinoSegmentedControlApi {
  /// Constructor for [CupertinoSegmentedControlApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CupertinoSegmentedControlApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : golubetsVar_binaryMessenger = binaryMessenger,
        golubetsVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? golubetsVar_binaryMessenger;

  static const MessageCodec<Object?> golubetsChannelCodec = _GolubetsCodec();

  final String golubetsVar_messageChannelSuffix;

  /// Creates a new native view with the given [viewId] and initial [config].
  /// The [callback] will be used to send events back to Dart.
  Future<void> create(int viewId, CupertinoSegmentedConfig config) async {
    final golubetsVar_channelName = 'dev.bayori.golubets.platform_adaptive_widgets.CupertinoSegmentedControlApi.create$golubetsVar_messageChannelSuffix';
    final golubetsVar_channel = BasicMessageChannel<Object?>(
      golubetsVar_channelName,
      golubetsChannelCodec,
      binaryMessenger: golubetsVar_binaryMessenger,
    );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(<Object?>[viewId, config]);
    final golubetsVar_replyList = await golubetsVar_sendFuture as List<Object?>?;
    if (golubetsVar_replyList == null) {
      throw _createConnectionError(golubetsVar_channelName);
    } else if (golubetsVar_replyList.length > 1) {
      throw PlatformException(
        code: golubetsVar_replyList[0]! as String,
        message: golubetsVar_replyList[1] as String?,
        details: golubetsVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Updates an existing view identified by [viewId] with new [config].
  Future<void> update(int viewId, CupertinoSegmentedConfig config) async {
    final golubetsVar_channelName = 'dev.bayori.golubets.platform_adaptive_widgets.CupertinoSegmentedControlApi.update$golubetsVar_messageChannelSuffix';
    final golubetsVar_channel = BasicMessageChannel<Object?>(
      golubetsVar_channelName,
      golubetsChannelCodec,
      binaryMessenger: golubetsVar_binaryMessenger,
    );
    final Future<Object?> golubetsVar_sendFuture = golubetsVar_channel.send(<Object?>[viewId, config]);
    final golubetsVar_replyList = await golubetsVar_sendFuture as List<Object?>?;
    if (golubetsVar_replyList == null) {
      throw _createConnectionError(golubetsVar_channelName);
    } else if (golubetsVar_replyList.length > 1) {
      throw PlatformException(
        code: golubetsVar_replyList[0]! as String,
        message: golubetsVar_replyList[1] as String?,
        details: golubetsVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
